### ISSUE TITLE
Change the file title to use px

### ISSUE THREAD

**Issue by unitehenry** [striven-erp/striven-editor#71]
Change ```file-name-el``` from an ```<h4>``` to a ```<p>``` tag with a defined ```px``` ```font-size``` css class definition.

```css
.Striven-Editor p.file-name-el {
     font-size: 14px; /* this might be too large */
}
```
